"""
PROGRAM:    CLAXW
TITLE:      DEMO PROGRAM FOR LAX-WENDROFF METHOD
            FOR CONSERVATION EQUATION (U*U/2)X+UT=0
INPUT:      H, X-GRID SPACING
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            F(X), INITIAL CONDITION ON U, U(X,0) = F(X)
            P(T), BOUNDARY CONDITION, U(0,T) = P(T)
            E(X,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

