"""
PROGRAM:    IHEAT
TITLE:      DEMO PROGRAM FOR IMPLICIT AND CRANK-
            NICOLSON METHODS FOR UT = KAPPA*UXX
INPUT:      N, NUMBER OF X-SUBINTERVALS
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            KAPPA, DIFFUSIVITY VALUE
            (X1, X2), X-INTERVAL
            P(T), LEFT BOUNDARY CONDITION
            Q(T), RIGHT BOUNDARY CONDITION
            F(X), INITIAL CONDITION
            E(X,T), EXACT SOLUTION
            W, W=1 FOR IMPLICIT-W=.5 FOR CRANK-NICOLSON
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

