"""
PROGRAM:    EHEAT
TITLE:      DEMO PROGRAM FOR EXPLICIT METHOD
            FOR HEAT EQUATION, UT = KAPPA*UXX
INPUT:      N NUMBER OF X-SUBINTERVALS
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            KAPPA, DIFFUSIVITY VALUE
            (X1,X2), X-INTERVAL
            P(T), LEFT BOUNDARY CONDITION
            Q(T), RIGHT BOUNDARY CONDITION
            F(X), INITIAL CONDITION
            E(X,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""
