"""
PROGRAM:    IWAVE
TITLE:      DEMO PROGRAM FOR IMPLICIT METHOD
            FOR UTT = C1*C1*UXX
INPUT:      N, NUMBER OF X-SUBINTERVALS
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            C1, CELERITY VALUE
            (X1,X2), X-INTERVAL
            P1(T), LEFT BOUNDARY CONDITION
            P2(T), RIGHT BOUNDARY CONDITION
            F(X), INITIAL CONDITION FOR U
            G(X), INITIAL CONDITION FOR UT
            E(X,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

