"""
PROGRAM:    SLAXW
TITLE:      DEMO PROGRAM FOR LAX-WENDROFF METHOD
            FOR SYSTEM OF TWO EQUATIONS, AUX + UT = 0
INPUT:      H, X-GRID SPACING
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            FU(X) & FV(X), INITIAL CONDITION ON U & V
            EU(X,T) & EV(X,T), EXACT U & V SOLUTIONS
            A & B, COEFFICIENT MATRIX AND ITS SQUARE
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

