"""
PROGRAM:    EWAVE
TITLE:      DEMO PROGRAM FOR EXPLICIT METHOD
            FOR WAVE EQUATION, UTT = C*C*UXX
INPUT:      N, NUMBER OF X-SUBINTERVALS
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            (X1,X2), X-INTERVAL
            P1(T), LEFT BOUNDARY CONDITION
            P2(T), RIGHT BOUNDARY CONDITION
            F(X), INITIAL CONDITION ON U
            G(X), INITIAL CONDITION ON UT
            E(X,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

