"""
PROGRAM:    WENDI
TITLE:      DEMO PROGRAM FOR WENDROFF'S IMPLICIT
            METHOD FOR EQUATION UX + UT = 0
INPUT:      N, NUMBER OF X-SUBINTERVALS
            K, TIME STEP (K/H < 1 FOR STABILITY)
            TMAX, MAXIMUM COMPUTATION TIME
            (X1,X2), X-INTERVAL
            F(X), INITIAL CONDITION ON U, U(X,0) = F(X)
            P(T), BOUNDARY CONDITION, U(0,T) = P(T)
            E(X,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""
