"""
PROGRAM:    LLAXW
TITLE:      DEMO PROGRAM FOR LAX-WENDROFF METHOD
            FOR LINEAR EQUATION UX + UT = 0
INPUT:      H, X-GRID SPACING
            K, TIME STEP (K/H < 1 FOR STABILITY)
            TMAX, MAXIMUM COMPUTATION TIME
            F(X), INITIAL CONDITION ON U, U(X,0) = F(X)
            P(T), BOUNDARY CONDITION, U(0,T) = P(T)
            E(X,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

