"""
PROGRAM:    ADI
TITLE:      DEMO PROGRAM FOR ADI METHOD FOR
            UT = KAPPA*(UXX * UYY)
INPUT:      MMAX & NMAX, NUMBER OF X & Y-SUBINTERVALS
            K, TIME STEP
            TMAX, MAXIMUM COMPUTATION TIME
            KAPPA, DIFFUSIVITY VALUE
            (X1,X2) & (Y1,Y2), X & Y-INTERVALS
            P1(Y,T) & Q1(Y,T), LEFT & RIGHT BOUNDARY CONDITIONS
            P2(X,T) & Q2(X,T), UPPER & LOWER BOUNDARY CONDITIONS
            F(X,Y), INITIAL CONDITION
            E(X,Y,T), EXACT SOLUTION
OUTPUT:     NUMERICAL AND EXACT SOLUTION AT T=TMAX
"""

